name: Hello World
version: "1.0.3"
slug: hello_world
description: A simple Hello World FastAPI add-on
url: https://github.com/Ahmed9190/hello-world-addon
arch:
  - aarch64
  - amd64
init: false
ports:
  1880/tcp: 1880
homeassistant: "2022.12.0"
