name: Hello World
version: "1.0.0"
slug: hello_world
description: A simple Hello World FastAPI add-on
url: https://github.com/Ahmed9190/hello-world-addon
arch:
  - aarch64
  - amd64
init: false
map:
  - data:rw
ports:
  1880/tcp: 1880
